#!/usr/bin/env bash
# Generate and append a tenant service block to docker-compose.yaml.
#
# Replaces onboard-tenant.md step 8 — the one place where the LLM is asked
# to produce multi-property YAML from prose rules, and where a mistake
# (wrong indentation, missing external: true, missing name:, missing watchdog
# labels, missing healthcheck) produces errors that check-tenant.sh does not
# fully catch.
#
# This script generates the block deterministically from the correct template
# and appends it to the existing file, preserving all other services.
#
# Usage:
#   add-tenant-compose-service.sh {tenant-id}
#
# Environment overrides (for testing):
#   PLATFORM_ROOT   (default: /opt/aaas/platform)
#   TENANT_ROOT     (default: /opt/aaas/tenants)

set -euo pipefail

TENANT_ID="${1:-}"
PLATFORM_ROOT="${PLATFORM_ROOT:-/opt/aaas/platform}"
TENANT_ROOT="${TENANT_ROOT:-/opt/aaas/tenants}"
COMPOSE_FILE="$PLATFORM_ROOT/docker/docker-compose.yaml"
TENANT_DIR="$TENANT_ROOT/$TENANT_ID"

usage() {
  echo "Usage: $0 {tenant-id}" >&2
}

fail() {
  echo "FAIL  $1" >&2
  exit 1
}

if [ -z "$TENANT_ID" ] || [[ "$TENANT_ID" == -* ]]; then
  usage
  fail "missing or invalid tenant-id"
fi

# --- Pre-conditions ---

[ -f "$COMPOSE_FILE" ] \
  || fail "docker-compose.yaml not found: $COMPOSE_FILE — run platform setup first"

[ -d "$TENANT_DIR" ] \
  || fail "tenant directory not found: $TENANT_DIR — create tenant files before calling this script"

[ -f "$TENANT_DIR/.env" ] \
  || fail "tenant .env not found: $TENANT_DIR/.env — render tenant files before calling this script"

# Guard: refuse to add a duplicate service entry
if grep -q "^  hermes_${TENANT_ID}:" "$COMPOSE_FILE" 2>/dev/null; then
  echo "SKIP  service hermes_${TENANT_ID} already present in $COMPOSE_FILE"
  echo "      If you are re-onboarding, remove the old block manually before re-running."
  exit 0
fi

# --- Generate the service block ---
#
# Every field here comes from the onboard-tenant.md step 8 prose spec.
# The three fields that check-tenant.sh does NOT verify — and that are
# therefore most likely to be mis-generated by a free-form LLM pass —
# are included here with their exact required values:
#   healthcheck.test        pgrep-based process check (no port published)
#   labels                  aaas.watchdog + priority 5 + playbook
#   networks (bottom block) external: true + name: hermes-{id}-net

cat >> "$COMPOSE_FILE" << EOF

  hermes_${TENANT_ID}:
    image: hermes-tenant:latest
    container_name: hermes_${TENANT_ID}
    command: /opt/data/scripts/tenant-entrypoint.sh
    restart: unless-stopped
    env_file:
      - ${TENANT_DIR}/.env
    volumes:
      - ${TENANT_DIR}:/opt/data
      - ${TENANT_DIR}/files:/home/hermes/files
      - ${TENANT_DIR}/vault:/home/hermes/vault
    mem_limit: 1g
    cpus: "1.0"
    networks:
      - hermes-${TENANT_ID}-net
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'gateway run' || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      aaas.watchdog: "true"
      aaas.watchdog.priority: "5"
      aaas.watchdog.playbook: "troubleshoot-tenant.md"
EOF

# --- Append the network declaration if not already present ---
#
# The explicit name: field is required — without it Compose project-prefixes
# the network name and `docker compose up` fails with "network not found".
# external: true tells Compose the network was created by provision-tenant-vault.md
# step 1a and must not be recreated.

if ! grep -q "^  hermes-${TENANT_ID}-net:" "$COMPOSE_FILE" 2>/dev/null; then
  # Ensure a top-level networks: section exists
  if ! grep -q "^networks:" "$COMPOSE_FILE" 2>/dev/null; then
    printf '\nnetworks:\n' >> "$COMPOSE_FILE"
  fi
  cat >> "$COMPOSE_FILE" << EOF
  hermes-${TENANT_ID}-net:
    name: hermes-${TENANT_ID}-net
    external: true
EOF
fi

echo "PASS  service hermes_${TENANT_ID} appended to $COMPOSE_FILE"
echo "PASS  network block hermes-${TENANT_ID}-net declared (external: true, name: hermes-${TENANT_ID}-net)"
echo ""
echo "Next: docker compose up -d hermes_${TENANT_ID}"
